write try catch in previous assignment which is auth-2



